// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsPGqV12Pl81MBtv1rXyOk3pANdEG-kY',
    appId: '1:591318299517:web:590eec7121d6e30db65214',
    messagingSenderId: '591318299517',
    projectId: 'mandailynassau',
    authDomain: 'mandailynassau.firebaseapp.com',
    storageBucket: 'mandailynassau.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0TTXGJHTkbfsn5QjR4laO8n8AF1XjMw',
    appId: '1:591318299517:android:26c6eb9aa69ca71bb65214',
    messagingSenderId: '591318299517',
    projectId: 'mandailynassau',
    storageBucket: 'mandailynassau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdFcqN_s1G7z1ArZjwt7pBKII5mTMNL_E',
    appId: '1:591318299517:ios:6e880d79fe8f2e9ab65214',
    messagingSenderId: '591318299517',
    projectId: 'mandailynassau',
    storageBucket: 'mandailynassau.firebasestorage.app',
    iosBundleId: 'com.example.mandaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdFcqN_s1G7z1ArZjwt7pBKII5mTMNL_E',
    appId: '1:591318299517:ios:6e880d79fe8f2e9ab65214',
    messagingSenderId: '591318299517',
    projectId: 'mandailynassau',
    storageBucket: 'mandailynassau.firebasestorage.app',
    iosBundleId: 'com.example.mandaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIsPGqV12Pl81MBtv1rXyOk3pANdEG-kY',
    appId: '1:591318299517:web:6ef00585c253c311b65214',
    messagingSenderId: '591318299517',
    projectId: 'mandailynassau',
    authDomain: 'mandailynassau.firebaseapp.com',
    storageBucket: 'mandailynassau.firebasestorage.app',
  );

}